version: '3.3'

configs:
  bf_config:
    file: ./config.php

networks:
  webnet:
    external:
      name: roach_cockroachdb

services:
  web:
    image: docker.cs.hioa.no/kyrrepublic/bf:latest

    configs:
      - source: bf_config
        target: /var/www/html/config.php
    ports:
      - "80"
    networks:
        - webnet

    environment:
      BF_MEMCACHE_SERVER: memcache

    deploy:
      replicas: 1

  memcache:
    image: memcached

    networks:
      - webnet
